import datetime

class MunicipalNoteGenerator:
    def generate(self, category: str, text: str, department: str, priority: str) -> str:
        date_str = datetime.date.today().strftime("%B %d, %Y")
        
        note = f"""OFFICIAL MUNICIPAL WORK ORDER
Date: {date_str}
Reference: CIVICAI-AUTO-GEN

TO:
{department}

SUBJECT:
Urgent Attention Required: {category} Grievance Reported

Dear Department In-Charge,

A citizen grievance has been automatically processed and validated by the CivicAI Intelligent Urban Monitoring system.

DETAILS OF THE GRIEVANCE:
- Grievance Category: {category}
- Assessed Priority: {priority}
- Reported Context: "{text if text else 'Visual inspection uploaded by citizen.'}"

AI SYSTEM ASSESSMENT & ACTIONS:
1. Automated image processing has validated the visual indicators of this issue.
2. Multilingual semantic extraction confirmed localized resident concerns.
3. The issue has been routed to your department based on structural classification.

Operational dispatch of a field inspection officer is recommended within 24 hours to initiate standard repairs.

Generated by CivicAI Governance Core.
Priority Level: {priority}
"""
        return note.strip()

note_generator = MunicipalNoteGenerator()
